name: Build APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 1. Libera espaço no servidor (evita erro de disco cheio)
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      # 2. Roda o Buildozer
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action-v1@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      # 3. Disponibiliza o APK para download
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
